- docs/concepts.mdx
- src/components/HomepageFeatures.js
This also includes some minor typo fixes on the homepage.
> Update concepts section to have cumulative&diff explainer

- wordlist.txt
This should fix spellcheck again.
> Add tooltip and ns to wordlist.txt

- docusaurus.config.js
- package.json
- yarn.lock
Dependabot is having trouble updating the deps individually and docusaurus even says to run at once:
```
yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/theme-search-algolia@latest
```
> Update docusaurus at once

- docs/community.md
Signed-off-by: Sumera Priyadarsini <sylphrenadin@gmail.com>
> docs/community: Improve contributing guidelines

- docs/kubernetes.mdx
> fix: Update kubernetes.mdx

- docusaurus.config.js
> Add Discord to the website's header

- docs/governance.md
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>
> Fix GitHub org link

- docs/binary.mdx
Fixes #156
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Tutorial Parca from Binary - Use same version for example as for the binary

- docs/governance.md
- wordlist.txt
> Add new team members Vaishali and Javier

- docs/snap.mdx
- docusaurus.config.js
- sidebars.js
Adds some basic docs about how to get started with the Snap package.
> Add snapcraft/snap package docs

- docs/governance.md
Add myself + sort by first name
> governance: Add Maxime to team members

- .github/workflows/spellcheck.yaml
- docs/parca-agent-labelling.md
- sidebars.js
- wordlist.txt
This probably should wait the next the release before merging
> feat: document profile labelling on the agent

- docs/parca-agent-design.md
> docs/parca-agent-design.md: Sync from Parca Agent repo

- docs/parca-agent-language-support.md
- wordlist.txt
I think it'd be nice to have more info on this page for people looking for their favorite language :)
> agent: Flesh out language support

- docusaurus.config.js
I see that this is the same as Tutorial, however, recently I struggled to find how to download Parca and certainly didn't expect it under Tutorial. Therefore, adding somewhat of duplication.
> Add Download button to header

- docs/parca-agent-labelling.md
> Add details for the 'java' label

- docs/quickstart.mdx
> fix: config is actually config-path

- sidebars.js
@brancz hope you don't mind the quick drive-by PR :)
> chore: Fix typo in sidebar

- docs/governance.md
> Add Tommy (gnurizen) as maintainer

- docs/governance.md
> Add Brennan as maintainer

- docs/configuration.md
added an s3 configuration example to the docs
> add s3 configuration example to main grafana server configuration doc
